import React from 'react'
import CardSlider from '../components/CardSlider'
function Configurations() {
  return (
   <>
    <CardSlider
        caption={{text:"Configurations",icon:"faGear"}}
          titles={["key","value","action"]}
          fields={[
            [{ type: "t", text: "sessionTimeout", size: 1 }, { type: "t", text: "30", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "maxLoginAttempts", size: 1 }, { type: "t", text: "5", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "passwordPolicy", size: 1 }, { type: "t", text: "min8chars,1upper,1number", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "emailNotifications", size: 1 }, { type: "t", text: "enabled", size: 1 }, { type: "i", text: "faPen", size: 1 }],
          
            // Generated by me
            [{ type: "t", text: "twoFactorAuth", size: 1 }, { type: "t", text: "enabled", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "dataRetentionDays", size: 1 }, { type: "t", text: "365", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "passwordExpiryDays", size: 1 }, { type: "t", text: "90", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "accountLockoutDuration", size: 1 }, { type: "t", text: "15min", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "ipWhitelist", size: 1 }, { type: "t", text: "192.168.0.0/24", size: 1 }, { type: "i", text: "faPen", size: 1 }],
            [{ type: "t", text: "apiRateLimit", size: 1 }, { type: "t", text: "1000req/min", size: 1 }, { type: "i", text: "faPen", size: 1 }]
          ]}
        />
   </>
  )
}

export default Configurations